Repository open-telemetry/opentelemetry-specification, pull requests merged in 2022-02, with the labels that each got.

#2308 Add instr-wg as code owers for semantic conventions.
  .github/CODEOWNERS
Labels: editorial

#2320 Pin markdownlint-cli version and apply fixes
  Makefile
  experimental/trace/zpages.md
  specification/glossary.md
  specification/metrics/api.md
  specification/metrics/datamodel.md
  specification/metrics/sdk.md
  specification/metrics/semantic_conventions/http-metrics.md
  specification/schemas/overview.md
  specification/sdk-environment-variables.md
  specification/trace/api.md
  specification/trace/semantic_conventions/http.md
  specification/trace/semantic_conventions/messaging.md
Labels: editorial

#2293 Fix a grammatical error in the python example.
  specification/metrics/api.md
Labels: editorial

#2321 [editorial]Add toc/tocstop to Logs pages
  Makefile
  specification/logs/data-model.md
  specification/logs/overview.md
  specification/logs/semantic_conventions/media.md
Labels: editorial

#2325 Clarify what does wildcard mean in the Metrics SDK View
  CHANGELOG.md
  specification/metrics/sdk.md
Labels: area:sdk, spec:metrics

#2334 [editorial] Improve display of compatibility matrix
  README.md
  spec-compliance-matrix.md
Labels: editorial

#2286 Add notes about MetricExporter naming
  specification/metrics/sdk.md
Labels: area:sdk, spec:metrics

#2276 Clarify that Trace/Meter are associated with Instrumentation Scope
  CHANGELOG.md
  spec-compliance-matrix.md
  specification/common/attribute-naming.md
  specification/glossary.md
  specification/metrics/api.md
  specification/metrics/sdk.md
  specification/trace/api.md
  specification/trace/sdk.md
  specification/trace/sdk_exporters/non-otlp.md
Labels: area:api, spec:metrics, spec:trace

#2344 Add `make all` target to test changes locally
  Makefile
Labels: editorial

#2351 [editorial] Add space in schemas/overview
  specification/schemas/overview.md
Labels: editorial

#2362 Add a CHANGELOG description for 2317 (Duplicate instrument registration)
  CHANGELOG.md
Labels: editorial

#2360 Refactor the Metrics API specification for instruments
  specification/metrics/api.md
  specification/metrics/sdk.md
  specification/metrics/supplementary-guidelines.md
Labels: area:api, spec:metrics
