Repository open-telemetry/opentelemetry-specification, pull requests merged in 2023-11, with the labels that each got.

#3765 Refer to W3C working draft versions
  specification/baggage/api.md
  specification/context/api-propagators.md
  specification/logs/README.md
  specification/protocol/exporter.md
  specification/resource/sdk.md
Labels: editorial

#3758 Move attribute documents to semantic-conventions repository
  specification/common/README.md
  specification/common/attribute-naming.md
  specification/common/attribute-requirement-level.md
  specification/common/url.md
Labels: Stale

#3749 Merge event's domain and name
  CHANGELOG.md
  specification/logs/event-api.md
  specification/versioning-and-stability.md
Labels: spec:logs, triaged-accepted
