Repository open-telemetry/opentelemetry-specification, pull requests merged in 2023-06, with the labels that each got.

#3526 Make recommendation to reserve aggregator normative
  specification/metrics/sdk.md
Labels: editorial

#3537 Simplify language for async API use outside of callback
  specification/metrics/sdk.md
Labels: area:sdk, spec:metrics, editorial

#3553 [editorial] Ensure trace subsections have a README
  specification/trace/api.md
  specification/trace/sdk.md
  specification/trace/sdk_exporters/README.md
  specification/trace/sdk_exporters/jaeger.md
  specification/trace/sdk_exporters/zipkin.md
  specification/trace/tracestate-handling.md
  specification/trace/tracestate-probability-sampling.md
Labels: editorial

#3541 Do not check for valid links in semantic conventions.
  Makefile
Labels: Stale

#3529 Make SDK Tracer/Meter/Logger Creation more normative
  CHANGELOG.md
  specification/logs/sdk.md
  specification/metrics/sdk.md
  specification/trace/sdk.md
Labels: area:sdk, spec:metrics

#3538 Clarify duplicate instrument registration scope to be a MeterProvider
  specification/metrics/sdk.md
Labels: editorial
