Repository open-telemetry/opentelemetry-specification, pull requests merged in 2023-10, with the labels that each got.

#3660 Prometheus exporters omit empty resources and scopes without attributes
  CHANGELOG.md
  specification/compatibility/prometheus_and_openmetrics.md
Labels: Stale

#3714 Fix description of OTEL_ATTRIBUTE_COUNT_LIMIT
  specification/configuration/sdk-environment-variables.md
Labels: editorial, area:configuration

#3718 Fix note references in protocol/exporter.md
  specification/protocol/exporter.md
Labels: editorial

#3437 Define file configuration parse and create operations
  CHANGELOG.md
  specification/configuration/file-configuration.md
Labels: area:sdk, area:configuration

#3728 [chore] protocol/exporter: Remove old reference
  specification/protocol/exporter.md
Labels: editorial
