Repository open-telemetry/opentelemetry-specification, pull requests merged in 2024-10, with the labels that each got.

#4237 Editorial - add links to Metric instrument parameters
  specification/metrics/api.md
Labels: editorial

#4245 Mark MetricReader cardinality limit as stable
  specification/metrics/sdk.md
Labels: editorial

#4240 Make the end timestamp and mutable span as requirements in onending
  specification/trace/sdk.md
Labels: spec:trace, clarification

#4267 Clarify OTEL_LOG_LEVEL is to control internal logging
  specification/configuration/sdk-environment-variables.md
Labels: editorial

#4197 Introduce specification for OTel Profiles
  CHANGELOG.md
  specification/README.md
  specification/profiles/README.md
  specification/profiles/mappings.md
Labels: spec:profiling
