Repository open-telemetry/opentelemetry-specification, pull requests merged in 2024-05, with the labels that each got.

#4019 Stabilize synchronous gauge
  CHANGELOG.md
  specification/metrics/api.md
Labels: area:api, spec:metrics

#3975 [configuration] Add example using hexadecimal notation
  specification/configuration/file-configuration.md
Labels: Stale

#4040 Consolidate Spec Matrix - part2
  spec-compliance-matrix.md
Labels: editorial

#4043 Remove redundant usage of "interface" after API
  specification/logs/event-api.md
  specification/metrics/sdk.md
Labels: editorial

#4047 [Editorial] Use standard SPC characters
  CHANGELOG.md
Labels: editorial

#4050 Fix a typo in logging specification
  specification/logs/README.md
Labels: editorial

#4059 add 'create a new gauge' to meter operations
  specification/metrics/api.md
Labels: editorial

#4057 Clarify that unit must be a suffix for metric names for Prometheus
  CHANGELOG.md
  specification/compatibility/prometheus_and_openmetrics.md
Labels: spec:metrics

#4020 Add Enabled method to Logger
  CHANGELOG.md
  spec-compliance-matrix.md
  specification/logs/bridge-api.md
Labels: area:api, spec:logs

#4064 Clarify the trace SDK should log discarded events and links
  CHANGELOG.md
  specification/trace/sdk.md
Labels: spec:trace
