Repository open-telemetry/opentelemetry-specification, pull requests merged in 2024-03, with the labels that each got.

#3912 Formalize the overflow and cardinality limit interaction
  CHANGELOG.md
  specification/metrics/sdk.md
Labels: area:sdk, spec:metrics

#3887 Mark the AddLink() operation as stable.
  specification/trace/api.md
Labels: Stale

#3919 [Editorial] fix a typo in the supplementary-guidelines.md
  specification/logs/supplementary-guidelines.md
Labels: editorial

#3939 [editorial] Logs > Exporters > Stdout - drop leading "OpenTelemetry" from the page title
  specification/logs/sdk_exporters/stdout.md
Labels: editorial

#3947 (docs) fix bad json in examples of log
  specification/protocol/file-exporter.md
Labels: editorial

#3898 Clarify that ReadableLogRecord and ReadWriteLogRecord can be represented using a single type
  CHANGELOG.md
  specification/logs/sdk.md
Labels: spec:logs
