Repository open-telemetry/opentelemetry-specification, pull requests merged in 2024-09, with the labels that each got.

#4178 Refactor description of span kind
  CHANGELOG.md
  specification/trace/api.md
Labels: Stale

#4067 Log record mutations are visible in next registered processors
  CHANGELOG.md
  specification/logs/sdk.md
Labels: spec:logs, clarification

#4173 Clarify logs export concurrency
  CHANGELOG.md
  specification/logs/sdk.md
Labels: spec:logs, clarification

#4186 Add natively instrumented to glossary
  CHANGELOG.md
  specification/glossary.md
Labels: Stale

#4209 chore: fix broken link
  specification/metrics/data-model.md
Labels: editorial

#4206 Clarify metrics export concurrency
  CHANGELOG.md
  specification/metrics/sdk.md
Labels: area:sdk, spec:metrics, clarification

#4210 Add issue triage helper
  .github/scripts/triage-helper/Pipfile
  .github/scripts/triage-helper/Pipfile.lock
  .github/scripts/triage-helper/app.py
  .github/workflows/triage-followup.yml
Labels: triage:deciding:tc-inbox

#3990 Document issue triage labels
  issue-management.md
Labels: Stale

#4216 Minor fixes of typos in trace/{sdk,api}.md
  specification/trace/api.md
  specification/trace/sdk.md
Labels: editorial

#4203 Define Enabled parameters for Logger
  CHANGELOG.md
  specification/logs/bridge-api.md
Labels: enhancement, area:api, spec:logs

#4228 Clarify cardinality capping should be after filtering
  CHANGELOG.md
  specification/metrics/sdk.md
Labels: clarification

#4205 Clarify spans export concurrency
  CHANGELOG.md
  specification/trace/sdk.md
Labels: area:sdk, spec:trace, clarification

#4217 Fixes switched columns of expected samples in trace sampling statistical requirement test non-power-of-two case
  specification/trace/tracestate-probability-sampling-experimental.md
Labels: editorial
