Repository open-telemetry/opentelemetry-specification, pull requests merged in 2025-05, with the labels that each got.

#4490 [API.Context] Drop reference to binary propagator
  CHANGELOG.md
  specification/context/api-propagators.md
Labels: spec:context, editorial

#4489 [Logs] Add optional Event Name parameter to Logger.Enabled and LogRecordProcessor.Enabled
  CHANGELOG.md
  specification/logs/api.md
  specification/logs/sdk.md
Labels: changelog.opentelemetry.io

#4511 Fix markdown link check
  .lychee.toml
  Makefile
Labels: editorial

#4516 Fix semconv links
  specification/overview.md
  specification/resource/sdk.md
  specification/semantic-conventions.md
Labels: editorial

#4498 [entities] Define rules for setting identifying attributes
  specification/entities/data-model.md
Labels: changelog.opentelemetry.io
